### ISSUE TITLE
Iris Framework Router Integration / Middleware

### ISSUE THREAD

**Issue by selopia909** [bartventer/gorm-multitenancy#51]
Would it be possible to get support for the [Iris Framework](https://github.com/kataras/iris), similar to what's available for Echo, Gin, and Net/Http? This enhancement would greatly assist us in implementing multi-tenant support across several of our existing projects. I appreciate any help you can provide.

**Comment by bartventer** [comment]
Thanks @selopia909, I'm currently working on adding support for the Iris Framework. I'll include it in the next release.
